spring:
  data:
    mongodb:
      uri: mongodb://mongo-1:27017,mongo-2:27018,mongo-3:27019/movies?replicaSet=mdbdefGuide
  redis:
    host: localhost
    port: 6379
    timeout: 100ms
logging:
  level:
    org.springframework.data.mongodb: DEBUG
