version: "3.6"

services:
  mongo-1:
    image: mongo
    build:
      context: .
      dockerfile: dockerfile
    container_name: mongo-1
    volumes:
      - ~/data/mongoRepl/rs1:/data/db
    ports:
      - "27017:27017"
    networks:
      - mongo-networks
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "mdbdefGuide" ]

  mongo-2:
    image: mongo
    container_name: mongo-2
    volumes:
      - ~/data/mongoRepl/rs2:/data/db
    ports:
      - "27018:27017"
    networks:
      - mongo-networks
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "mdbdefGuide" ]

  mongo-3:
    image: mongo
    container_name: mongo-3
    volumes:
      - ~/data/mongoRepl/rs3:/data/db
    ports:
      - "27019:27017"
    networks:
      - mongo-networks
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "mdbdefGuide" ]

networks:
  mongo-networks:
    driver: bridge
